# -*- coding: utf-8 -*-
"""
Created on Tue Apr 18 14:41:44 2017

@author: DREAM
"""

import prt1
from time import sleep

def sw0000():
    prt1.prtcent("  *                                 *     ")
    prt1.prtcent("                          *               ")
    prt1.prtcent("           *                         *    ")
    prt1.prtcent("   _____  _____  ______          __  __   ")
    prt1.prtcent("  |  __ \|  __ \|  ____|   /\   |  \/  |  ")
    prt1.prtcent("* | |  | | |__) | |__     /  \  | \  / |  ")
    prt1.prtcent("  | |  | |  _  /|  __|   / /\ \ | |\/| |  ")
    prt1.prtcent("  | |  | | | \ \| |____ / ____ \| |  | |  ")
    prt1.prtcent("  | |__| |_|  \_\______/_/    \_\ |  | |  ")
    prt1.prtcent("  |_____/  E N T E R P R I S E  |_|  |_|  ")
    prt1.prtcent("      *                                *  ")
    prt1.prtcent("www.DREAM-Enterprise.com")
    prt1.prtcent("                *              *          ")
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    sleep(3)
    
    prt1.prtcent("                                _       ")
    prt1.prtcent("                               | |      ")
    prt1.prtcent(" _ __  _ __ ___  ___  ___ _ __ | |_ ___ ")
    prt1.prtcent("| '_ \| '__/ _ \/ __|/ _ \ '_ \| __/ __|")
    prt1.prtcent("| |_) | | |  __/\__ \  __/ | | | |_\__ \\")
    prt1.prtcent("| .__/|_|  \___||___/\___|_| |_|\__|___/")
    prt1.prtcent("| |                                     ")
    prt1.prtcent("|_|                                     ")
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    sleep(2)
    
    prt1.prtcent("            _______ _     _             ")
    prt1.prtcent("    /\     |__   __| |   (_)            ")
    prt1.prtcent("   /  \       | |  | |__  _ _ __   __ _ ")
    prt1.prtcent("  / /\ \      | |  | '_ \| | '_ \ / _` |")
    prt1.prtcent(" / ____ \     | |  | | | | | | | | (_| |")
    prt1.prtcent("/_/    \_\    |_|  |_| |_|_|_| |_|\__, |")
    prt1.prtcent("                                   __/ |")
    prt1.prtcent("                                  |___/ ")
    prt1.prtcent(" _____       _____  _     _ ")
    prt1.prtcent("|_   _|     |  __ \(_)   | |")
    prt1.prtcent("  | |       | |  | |_  __| |")
    prt1.prtcent("  | |       | |  | | |/ _` |")
    prt1.prtcent(" _| |_      | |__| | | (_| |")
    prt1.prtcent("|_____|     |_____/|_|\__,_|")
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    sleep(3)
    prt1.cutpaper()
    sleep(1)

def sw0001():
    prt1.prtcent("A long time ago in a galaxy far,")
    prt1.prtcent("far away...                     ")
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    sleep(4)
    prt1.linefeed()
    sleep(2)
    
    prt1.prtcent("    8888888888  888    88888       ")
    prt1.prtcent("   88     88   88 88   88  88      ")
    prt1.prtcent("    8888  88  88   88  88888       ")
    prt1.prtcent("       88 88 888888888 88   88     ")
    prt1.prtcent("88888888  88 88     88 88    888888")
    prt1.prtcent("\n") 
    prt1.prtcent("88  88  88   888    88888    888888")
    prt1.prtcent("88  88  88  88 88   88  88  88     ")
    prt1.prtcent("88 8888 88 88   88  88888    8888  ")
    prt1.prtcent(" 888  888 888888888 88   88     88 ")
    prt1.prtcent("  88  88  88     88 88    8888888  ")
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    
    sleep(5)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    
    prt1.prtcent("Episode IV")
    sleep(1)
    prt1.prtcent("A NEW HOPE")
    sleep(1)
    prt1.prtcent("It is a period of civil war.")
    sleep(1)
    prt1.prtcent("Rebel spaceships, striking")
    sleep(1)
    prt1.prtcent("from a hidden base, have won")
    sleep(1)
    prt1.prtcent("their first victory against")
    sleep(1)
    prt1.prtcent("the evil Galactic Empire.")
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.prtcent("During the battle, Rebel")
    sleep(1)
    prt1.prtcent("spies managed to steal secret")
    sleep(1)
    prt1.prtcent("plans to the Empire's")
    sleep(1)
    prt1.prtcent("ultimate weapon, the DEATH")
    sleep(1)
    prt1.prtcent("STAR, an armored space")
    sleep(1)
    prt1.prtcent("station with enough power")
    sleep(1)
    prt1.prtcent("to destroy an entire planet.")
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.prtcent("Pursued by the Empire's")
    sleep(1)
    prt1.prtcent("sinister agents, Princess")
    sleep(1)
    prt1.prtcent("Leia races home aboard her")
    sleep(1)
    prt1.prtcent("starship, custodian of the")
    sleep(1)
    prt1.prtcent("stolen plans that can save her")
    sleep(1)
    prt1.prtcent("people and restore")
    sleep(1)
    prt1.prtcent("freedom to the galaxy....")
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(1)
    prt1.linefeed()
    sleep(2)


def sw9001():
    prt1.linefeed()
    prt1.prtcent("                      /~\     ")
    prt1.prtcent("                     |oo )    ")
    prt1.prtcent("                     _\=/_    ")
    prt1.prtcent("     ___            /  _  \   ")
    prt1.prtcent("    / ()\          //|/.\|\\  ")
    prt1.prtcent("  _|_____|_        \\ \_/  || ")
    prt1.prtcent(" | | === | |        \|\ /| || ")
    prt1.prtcent(" |_|  O  |_|        # _ _/ #  ")
    prt1.prtcent("  ||  O  ||          | | |    ")
    prt1.prtcent("  ||__*__||          | | |    ")
    prt1.prtcent(" |~ \___/ ~|         []|[]    ")
    prt1.prtcent(" /=\ /=\ /=\         | | |    ")
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    sleep(5)

def sw9999():
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.prtcent("Inspired By")
    prt1.prtcent("http://www.asciimation.co.nz/")
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    prt1.linefeed()
    sleep(5)
    prt1.cutpaper()
    
    
if __name__ == "__main__":
    sw0000()
    sw0001()    
    
    sw9001()
    sw9999()
    prt1.end()